#
# MORE INFO:
#   https://docs.travis-ci.com/user/deployment/npm/
# Building JS Project
#   https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# Job Lifecycle
#   https://docs.travis-ci.com/user/job-lifecycle/
#

language: node_js
node_js:
    - "14"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"

deploy:
  -
    provider: npm
    email: "YOUR@EMAIL.ADDRESS"
    api_key: $NPM_API_KEY
    tag: next
    on:
        branch: next
  -
      provider: npm
      email: "YOUR@EMAIL.ADDRESS"
      api_key: $NPM_API_KEY
      on:
          tags: true
