language: node_js
node_js:
    - "10"
before_install:
    - npm install -g yarn
before_script:
    - cd packages/react-workbox
deploy:
    provider: npm
    email: "YOUR@EMAIL.ADDRESS"
    api_key: $NPM_API_KEY
    on:
        tags: true
